# Generated by Django 3.2.6 on 2021-09-07 18:53

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_customuser_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zip',
            field=models.CharField(default='97217', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=localflavor.us.models.USStateField(default='OR', max_length=2, null=True),
        ),
    ]
