# Generated by Django 3.2.6 on 2021-09-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210908_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lon',
        ),
    ]
